// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _202009021351377_newDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202009021351377_newDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202009022138365_[202009021351377_newDB]"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
